name: Run tests with coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      working-directory: ${{ github.workspace }}/100of100Service
      run: mvn -B package --file pom.xml
      
    - name: Install dependencies
      run: npm install

    - name: Run tests
      working-directory: ${{ github.workspace }}/100of100Service
      run: npx jest --coverage

    - name: Upload results to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
